name: origins-paper-test

services:
  paper:
    image: docker.io/itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      - ./paper:/data:z
    environment:
      EULA: "TRUE"
      VERSION: "1.21.11"
      TYPE: "PAPER"
      MEMORY: "4G"
    userns_mode: "keep-id"