on load:
    register a new ability with key "cubbscratchstudios:curl_up" and title "Curl Up" and description "You can curl up into a ball whilst sneaking, giving you resistance and slowness"

on sneak toggle:
    if player has ability "cubbscratchstudios:curl_up":
        if player is not sneaking:
            if player is not gliding:
                apply resistance 4 to the player for 5 seconds
                apply slowness 4 to the player for 5 seconds

                wait 0.5 seconds
                while player is sneaking:
                    apply resistance 4 to the player for 5 seconds
                    apply slowness 4 to the player for 5 seconds

                    wait 0.5 seconds
                remove resistance from player
                remove slowness from player
