on load:
	register a new ability with key "cubbscratchstudios:frog_jump" and title "Frog Leap" and description "Double left-clicking while sneaking allows you to leap into the air."
	
on left click:
	if player has ability "cubbscratchstudios:frog_jump":
		if player is sneaking:
			if player is on ground:
				if {cooldown::%uuid of player%::frog_boost} is set:
					if {cooldown::%uuid of player%::frog_boost} was less than 15 seconds ago:
						play sound "minecraft:block.note_block.bass" to player
						exit
						
				if {cooldown::%uuid of player%::frog_boost_timeout} is not set:
					set {_prompt_bar} to boss bar with id "cooldown__%uuid of player%__frog_jump_prompt" with title "Double click to leap!" with color white with progress 100
					add player to {_prompt_bar}
					set {cooldown::%uuid of player%::frog_boost_timeout} to now
					wait 0.5 seconds
					delete boss bar with id "cooldown__%uuid of player%__frog_jump_prompt"
					exit
					
				if {cooldown::%uuid of player%::frog_boost_timeout} was more than 0.4 seconds ago:
					set {cooldown::%uuid of player%::frog_boost_timeout} to now
					wait 0.5 seconds
					if {cooldown::%uuid of player%::frog_boost_timeout} was more than 0.4 seconds ago:
						set {_prompt_bar} to boss bar with id "cooldown__%uuid of player%__frog_jump_prompt" with title "Double click to leap!" with color white with progress 100
						add player to {_prompt_bar}
						wait 0.5 seconds
						delete boss bar with id "cooldown__%uuid of player%__frog_jump_prompt"
					exit
					
				set {cooldown::%uuid of player%::frog_boost} to now
				set {cooldown::%uuid of player%::frog_boost_timeout} to now
				
				push player up with a speed of 2
				
				set {_cd_bar} to boss bar with id "cooldown__%uuid of player%__frog_jump" with title "Frog Leap" with color white with progress 0
				add player to {_cd_bar}
				
				while {cooldown::%uuid of player%::frog_boost} was less than 15 seconds ago:
					set {_t} to difference between now and {cooldown::%uuid of player%::frog_boost}
					set bar progress of {_cd_bar} to seconds of {_t} * 20/3
					wait 0.5 seconds
					
				delete boss bar with id "cooldown__%uuid of player%__frog_jump"
