on load:
    register a new ability with key "cubbscratchstudios:wind_jump" and title "Wind Jump" and description "You release a wind charge when sneaking, allowing you to boost yourself into the air."


on sneak toggle:
    if player has ability "cubbscratchstudios:wind_jump":
        if player is not sneaking:
            if player is on ground:
                if {cooldown::%uuid of player%::wind_jump} is set:
                    if {cooldown::%uuid of player%::wind_jump} was less than 5 seconds ago:
                        send "<red>5s cooldown! %time since {cooldown::%uuid of player%::wind_jump}% elapsed..." to player
                        exit

                summon wind charge at player:
                    detonate the wind charge

                set {cooldown::%uuid of player%::wind_jump} to now

                set {_cd_bar} to boss bar with id "cooldown__%uuid of player%__wind_jump" with title "Wind Jump" with color white with progress 0
                add player to {_cd_bar}

                while {cooldown::%uuid of player%::wind_jump} was less than 5 seconds ago:
                    set {_t} to difference between now and {cooldown::%uuid of player%::wind_jump}
                    set bar progress of {_cd_bar} to seconds of {_t} * 20
                    wait 0.5 seconds

                delete boss bar with id "cooldown__%uuid of player%__wind_jump"